CREATE EXTENSION IF NOT EXISTS vector CASCADE;
CREATE EXTENSION IF NOT EXISTS pgml CASCADE;
CREATE EXTENSION IF NOT EXISTS embedding CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_cron CASCADE;
CREATE EXTENSION IF NOT EXISTS pgmq CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_later CASCADE;
SELECT pglater.init();
CREATE EXTENSION IF NOT EXISTS vectorize CASCADE;
